name: CD

on:
  push:
    branches:
      - main
      - release/**

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ZUPIT_BOT_GITHUB_TOKEN }}

      - name: Setup git user
        run: |
          git config user.name "${{ vars.ZUPIT_BOT_USER_NAME }}"
          git config user.email "${{ vars.ZUPIT_BOT_USER_EMAIL }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ZUPIT_BOT_NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Release & Publish
        run: npx nx affected --target=release --parallel=1 -- --base-branch=${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.ZUPIT_BOT_GITHUB_TOKEN }}
