name: CI

on:
  pull_request:
    branches:
      - main
      - release/**

jobs:
  main:
    name: Main
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 3
      parallel-commands-on-agents: |
        npx nx affected --target=build --parallel=3 & \
        npx nx affected --target=format --parallel=3 & \
        npx nx affected --target=lint --parallel=3 & \
        npx nx affected --target=test --parallel=3 --ci --code-coverage & \
        npx nx affected --target=e2e --parallel=3

  agents:
    name: Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3

  checks:
    name: Checks
    needs: [main, agents]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Checks
        run: npx nx affected --target=build,format,lint,test,e2e --parallel=3
