name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Main
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 3
      parallel-commands-on-agents: |
        npx nx affected --target=format --parallel=3 & npx nx affected --target=lint --parallel=3 & npx nx affected --target=build --parallel=3 & npx nx affected --target=test --parallel=3 & npx nx affected --target=e2e --parallel=3

  agents:
    name: Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
