name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-npm:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ZUPIT_BOT_TOKEN }}
      - name: Setup git user
        run: |
          git config user.name "ZupitDevs"
          git config user.email "49716732+ZupitDevs@users.noreply.github.com"
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm ci --ignore-scripts
      - name: Release
        shell: bash
        run: npx nx affected --target=release --parallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.ZUPIT_BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
