name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci --ignore-scripts
      - name: Version
        shell: bash
        run: npx nx affected --target=release --parallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.ZUPIT_BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.ZUPIT_BOT_TOKEN }}